version: '3.8'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'ecommerce'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '1234'
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      - '3306:3306'
    volumes:
      - 'mysqldata:/var/lib/mysql'

    networks:
      - ecommerce_test

  redis_container:
    image: redis:latest
    container_name: redis_test
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/conf/redis.conf

    labels:
      - "name=redis"
      - "mode=standalone"

    networks:
      - ecommerce_test

    command: redis-server /usr/local/conf/redis.conf

  controller:
    image: ngrinder/controller
    ports:
      - "9000:80"
      - "16001:16001"
      - "12000-12009:12000-12009"
    volumes:
      - ./ngrinder-controller:/opt/ngrinder-controller

    networks:
      - ecommerce_test
  agent:
    image: ngrinder/agent
    links:
      - controller
    networks:
      - ecommerce_test

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-stream
    volumes:
      - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_ERLANG_COOKIE: "RabbitMQ-My-Cookies"
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"

    networks:
      - ecommerce_test

volumes:
  mysqldata:

networks:
  ecommerce_test:
