version: '3'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'ecommerce'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '1234'
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      - '3306:3306'
    volumes:
      - 'mysqldata:/var/lib/mysql'

    restart: always
volumes:
  mysqldata:
