server:
  port: 8083

route:
  member-api:
    v1:
      base-url: http://member-api:8080

  ecommerce-api:
    v1:
      base-url: http://ecommerce-api:8081

spring:
  config:
    import:
      - redis.yml
  cloud:
    gateway:
      default-filters:
        - name : AuthFilter

exclude:
  uri: /api/v1/members/signup, /api/v1/members/login

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        failure-rate-threshold: 50
        slow-call-rate-threshold: 80
        slow-call-duration-threshold: 10s
        permitted-number-of-calls-in-half-open-state: 3
        max-wait-duration-in-half-open-state: 0
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 10
        wait-duration-in-open-state: 10s
    instances:
      ecommerce-circuit-breaker:
        base-config: default
      member-circuit-breaker:
        base-config: default
