spring:
  config:
    activate:
      on-profile: prod

route:
  member-api:
    v1:
      base-url: http://member-api:8080

  ecommerce-api:
    v1:
      base-url: http://ecommerce-api:8081

  product-api:
    v1:
      base-url: http://product-api:8085

  order-api:
    v1:
      base-url: http://order-api:8086
