server:
  port: 8083

route:
  member-api:
    v1:
      base-url: http://localhost:8080

  ecommerce-api:
    v1:
      base-url: http://localhost:8081

spring:
  config:
    import:
      - redis.yml
  cloud:
    gateway:
      default-filters:
        - name : AuthFilter

exclude:
  uri: /api/v1/members/signup, /api/v1/members/login
