spring:
  config:
    activate:
      on-profile: local,test

  data:
    redis:
      host: localhost
      port: 6379

    redis2:
      host: localhost
      port: 6380

  session:
    store-type: redis

server:
  servlet:
    session:
      cookie:
        name: JSESSIONID
---
spring:
  config:
    activate:
      on-profile: prod

  data:
    redis:
      host: redis_test
      port: 6379

    redis2:
      host: 172.30.1.
      port: 6380

  session:
    store-type: redis

server:
  servlet:
    session:
      cookie:
        name: JSESSIONID
